[package]
name = "prom_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.package]
version = "0.1.1"
edition = "2021"
license = "Apache-2.0"

[workspace]
members = ["lib/promql", "lib/function-macro"]

[dependencies]
anyhow = "1.0"
bytes = "1.4"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
dashmap = { version = "5.4.0", features = ["serde"] }
parquet = { version = "36.0", features = ["arrow", "async"] }
arrow = { version = "36.0", features = ["simd", "ipc_compression"] }
arrow-schema = { version = "36.0", features = ["serde"] }
datafusion = { git = "https://github.com/apache/arrow-datafusion.git", rev = "8e125d2ecf242b4f4b81f06839900dbb2037cc2a" }
datafusion-common = { git = "https://github.com/apache/arrow-datafusion.git", rev = "8e125d2ecf242b4f4b81f06839900dbb2037cc2a" }
datafusion-expr = { git = "https://github.com/apache/arrow-datafusion.git", rev = "8e125d2ecf242b4f4b81f06839900dbb2037cc2a" }
datafusion-optimizer = { git = "https://github.com/apache/arrow-datafusion.git", rev = "8e125d2ecf242b4f4b81f06839900dbb2037cc2a" }
datafusion-physical-expr = { git = "https://github.com/apache/arrow-datafusion.git", rev = "8e125d2ecf242b4f4b81f06839900dbb2037cc2a" }
datafusion-sql = { git = "https://github.com/apache/arrow-datafusion.git", rev = "8e125d2ecf242b4f4b81f06839900dbb2037cc2a" }
promql-parser = "0.1.0"
parking_lot = "0.12"
time = "0.3.17"
lazy_static = "1.4.0"
async-trait = "0.1.57"
serde_json = "1.0"
env_logger = "0.10"
log = "0.4.17"

[build-dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock"] }
prost-build = "0.11"
tonic-build = { version = "0.8", features = ["prost"] }

[dev-dependencies]
expect-test = "1.4"
