[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[workspace]
members = ["newpromql", "cmd"]

[workspace.dependencies]
datafusion = "22"
serde = { version = "1.0", features = ["derive"] }
time = "0.3"
