apiVersion: v1
kind: Service
metadata:
  name: promtest
  namespace: prom-test
  labels:
    name: promtest
spec:
  selector:
    app: promtest
  ports:
  - name: http
    port: 5080
    targetPort: 5080

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: promtest
  namespace: prom-test
spec:
  serviceName: promtest
  replicas: 1
  selector:
    matchLabels:
      app: promtest
  template:
    metadata:
      labels:
        app: promtest
    spec:
      nodeSelector:
        node.kubernetes.io/instance-type: c2-standard-8
      containers:
        - name: promtest
          image: public.ecr.aws/zinclabs/prom-test-dev:latest
          ports:
          - containerPort: 5080
            name: http
          volumeMounts:
          - name: data
            mountPath: /app/samples
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      # storageClassName: default
      # NOTE: You can increase the storage size
      resources:
        requests:
          storage: 10Gi
