[package]
name = "function-macro"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = "1.0"
proc-macro2 = "1.0"

[dev-dependencies]
arc-swap = "1.0"
snafu.workspace = true
static_assertions = "1.1.0"
