[package]
name = "newpromql"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-recursion = "1.0"
async-trait.workspace = true
bytemuck = "1.12"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
datafusion.workspace = true
futures = "0.3"
promql-parser = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
snafu = { version = "0.7", features = ["backtraces"] }
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"
time = "0.3.17"
tracing.workspace = true
tracing-subscriber.workspace = true
md5 = "0.7"

[dev-dependencies]
tokio.workspace = true
